apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: my-deploy
          image: ghcr.io/${{ github.repository_owner }}/my-deploy:${{ github.sha }}
          ports:
            - containerPort: 80