apiVersion: apps/v1
kind: Deployment
metadata:
  name: kk-dep
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: krish
          image: machanikrishnakumar/ubuntu:latest
          ports:
            - containerPort: 80