name: Deployment in Minikube

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

jobs: 
  unit-testing:
    name: Unit-Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
    
  Docker:
    name: Containerization
    needs: [unit-testing]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Dockerhub
        uses: docker/login-action@v2.2.0 
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
     
      - name: Pull the Docker Image
        run: docker pull ubuntu:latest

      - name: List the Images
        run: docker images
      
      - name: Tag the images
        run: docker tag ubuntu:latest ${{ vars.DOCKER_USERNAME }}/ubuntu:latest
      
      - name: list the images
        run: docker images
      
      - name: Run the image
        run: docker run --name krish ${{ vars.DOCKER_USERNAME }}/ubuntu:latest

      - name: List the containers
        run: docker ps -a

      - name: start the container
        run: docker start krish
      
      - name: List the containers
        run: docker ps -a

      - name: Docker push
        run: |
          docker push ${{ vars.DOCKER_USERNAME }}/ubuntu:latest

      - name: checkout repo
        uses: actions/checkout@v4 
      
      - name: start minikube
        id: minikube
        uses: medyagh/setup-minikube@latest

      - name: Get the Cluster Info
        run: kubectl get pods -n default

      - name: Install Ingress Controller
        run: |
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/cloud/deploy.yaml
          kubectl rollout status -n ingress-nginx deploy/ingress-nginx-controller 

      - name: get tne services
        run: kubectl get svc -n ingress-nginx

      - name: Apply the Deployment files
        run: | 
          kubectl apply -f ./deployment.yaml
          kubectl apply -f ./ingress-service.yaml
         
      - name: Check the pods
        run: |
           for i in {1..5}; do
            kubectl get pods --all-namespaces
            echo "Iteration #$i: Checking pods"
            kubectl get pods --all-namespaces
            echo "Iteration #$i: Checking pods"
            kubectl get pods --all-namespaces
            kubectl get svc --all-namespaces
            echo "Waiting for 30 seconds before next iteration..."
            sleep 30  # 30-second gap between iterations
           done
           minikube ip
        
      - name: Get Minikube IP
        id:   minikube_ip
        run: |
              echo "MINIKUBE_IP=$(minikube ip)" >> $GITHUB_ENV

      - name: Get NodePort of the service
        id: nodeport
        run: |
          NODEPORT=$(kubectl get svc kk-svc -n ingress-nginx -o jsonpath='{.spec.ports[0].nodePort}')
          echo "NODEPORT=$NodePort" >> $GITHUB_ENV

      - name: Expose app via Minikube IP and NodePort
        run: |
          echo "App is exposed at: http://${{ env.MINIKUBE_IP }}:${{ env.NODEPORT }}"
          curl http://${{ env.MINIKUBE_IP }}:30080  # Optionally test the app
    
      

      
       



       