name: Deployment in Minikube

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

jobs: 
  unit-testing:
    name: Unit-Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
    
  Docker:
    name: Containerization
    needs: [unit-testing]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Dockerhub
        uses: docker/login-action@v2.2.0 
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD}}
     
      - name: Pull the Docker Image
        run: docker pull ubuntu:latest

      - name: List the Images
        run: docker images
      
      - name: Tag the images
        run: docker tag ${{ vars.DOCKER_USERNAME }}/ubuntu:latest

       